const THEMES = [
  { preview: "preview/theme-01-elegan-emas.jpg", file: "theme-01-elegan-emas.html", name: "Elegan Emas", cat: "Pernikahan", price: 150000 },
  { preview: "preview/theme-02-minimalis-modern.jpg", file: "theme-02-minimalis-modern.html", name: "Minimalis Modern", cat: "Pernikahan", price: 150000 },
  { preview: "preview/theme-03-putih-suci.jpg", file: "theme-03-putih-suci.html", name: "Putih Suci", cat: "Pernikahan", price: 150000 },
  { preview: "preview/theme-04-sage-rindu.jpg", file: "theme-04-sage-rindu.html", name: "Sage Rindu", cat: "Pernikahan", price: 225000 },
  { preview: "preview/theme-05-biru-senja.jpg", file: "theme-05-biru-senja.html", name: "Biru Senja", cat: "Pernikahan", price: 225000 },
  { preview: "preview/theme-06-marun-klasik.jpg", file: "theme-06-marun-klasik.html", name: "Marun Klasik", cat: "Pernikahan", price: 225000 },
  { preview: "preview/theme-07-peach-harmoni.jpg", file: "theme-07-peach-harmoni.html", name: "Peach Harmoni", cat: "Pernikahan", price: 225000 },
  { preview: "preview/theme-08-toska-bahagia.jpg", file: "theme-08-toska-bahagia.html", name: "Toska Bahagia", cat: "Pernikahan", price: 300000 },
  { preview: "preview/theme-09-maharaja-jawa.jpg", file: "theme-09-maharaja-jawa.html", name: "Maharaja Jawa", cat: "Pernikahan", price: 300000 },
  { preview: "preview/theme-10-kristal-mewah.jpg", file: "theme-10-kristal-mewah.html", name: "Kristal Mewah", cat: "Pernikahan", price: 300000 },
  { preview: "preview/khitanan-01-biru-mulia.jpg", file: "khitanan-01-biru-mulia.html", name: "Biru Mulia", cat: "Khitanan", price: 150000 },
  { preview: "preview/khitanan-02-putih-biru.jpg", file: "khitanan-02-putih-biru.html", name: "Putih Biru", cat: "Khitanan", price: 150000 },
  { preview: "preview/khitanan-03-hijau-segar.jpg", file: "khitanan-03-hijau-segar.html", name: "Hijau Segar", cat: "Khitanan", price: 150000 },
  { preview: "preview/khitanan-04-krem-lembut.jpg", file: "khitanan-04-krem-lembut.html", name: "Krem Lembut", cat: "Khitanan", price: 225000 },
  { preview: "preview/khitanan-05-navy-elegan.jpg", file: "khitanan-05-navy-elegan.html", name: "Navy Elegan", cat: "Khitanan", price: 225000 },
  { preview: "preview/khitanan-06-toska-ceria.jpg", file: "khitanan-06-toska-ceria.html", name: "Toska Ceria", cat: "Khitanan", price: 225000 },
  { preview: "preview/khitanan-07-abu-modern.jpg", file: "khitanan-07-abu-modern.html", name: "Abu Modern", cat: "Khitanan", price: 225000 },
  { preview: "preview/khitanan-08-raja-kecil.jpg", file: "khitanan-08-raja-kecil.html", name: "Raja Kecil", cat: "Khitanan", price: 300000 },
  { preview: "preview/khitanan-09-langit-emas.jpg", file: "khitanan-09-langit-emas.html", name: "Langit Emas", cat: "Khitanan", price: 300000 },
  { preview: "preview/khitanan-10-samudra-mewah.jpg", file: "khitanan-10-samudra-mewah.html", name: "Samudra Mewah", cat: "Khitanan", price: 300000 },
  { preview: "preview/aqiqah-01-peach-lembut.jpg", file: "aqiqah-01-peach-lembut.html", name: "Peach Lembut", cat: "Aqiqah", price: 150000 },
  { preview: "preview/aqiqah-02-krem-bayi.jpg", file: "aqiqah-02-krem-bayi.html", name: "Krem Bayi", cat: "Aqiqah", price: 150000 },
  { preview: "preview/aqiqah-03-putih-susu.jpg", file: "aqiqah-03-putih-susu.html", name: "Putih Susu", cat: "Aqiqah", price: 150000 },
  { preview: "preview/aqiqah-04-mint-lembut.jpg", file: "aqiqah-04-mint-lembut.html", name: "Mint Lembut", cat: "Aqiqah", price: 225000 },
  { preview: "preview/aqiqah-05-rose-bayi.jpg", file: "aqiqah-05-rose-bayi.html", name: "Rose Bayi", cat: "Aqiqah", price: 225000 },
  { preview: "preview/aqiqah-06-langit-bayi.jpg", file: "aqiqah-06-langit-bayi.html", name: "Langit Bayi", cat: "Aqiqah", price: 225000 },
  { preview: "preview/aqiqah-07-lavender-mimpi.jpg", file: "aqiqah-07-lavender-mimpi.html", name: "Lavender Mimpi", cat: "Aqiqah", price: 225000 },
  { preview: "preview/aqiqah-08-istana-bayi.jpg", file: "aqiqah-08-istana-bayi.html", name: "Istana Bayi", cat: "Aqiqah", price: 300000 },
  { preview: "preview/aqiqah-09-mutiara-kasih.jpg", file: "aqiqah-09-mutiara-kasih.html", name: "Mutiara Kasih", cat: "Aqiqah", price: 300000 },
  { preview: "preview/aqiqah-10-pelangi-ceria.jpg", file: "aqiqah-10-pelangi-ceria.html", name: "Pelangi Ceria", cat: "Aqiqah", price: 300000 },
  { preview: "preview/ultah-01-konfeti-ceria.jpg", file: "ultah-01-konfeti-ceria.html", name: "Konfeti Ceria", cat: "Ultah", price: 150000 },
  { preview: "preview/ultah-02-balon-warna.jpg", file: "ultah-02-balon-warna.html", name: "Balon Warna", cat: "Ultah", price: 150000 },
  { preview: "preview/ultah-03-kue-manis.jpg", file: "ultah-03-kue-manis.html", name: "Kue Manis", cat: "Ultah", price: 150000 },
  { preview: "preview/ultah-04-pita-ceria.jpg", file: "ultah-04-pita-ceria.html", name: "Pita Ceria", cat: "Ultah", price: 225000 },
  { preview: "preview/ultah-05-neon-party.jpg", file: "ultah-05-neon-party.html", name: "Neon Party", cat: "Ultah", price: 225000 },
  { preview: "preview/ultah-06-pastel-party.jpg", file: "ultah-06-pastel-party.html", name: "Pastel Party", cat: "Ultah", price: 225000 },
  { preview: "preview/ultah-07-retro-seru.jpg", file: "ultah-07-retro-seru.html", name: "Retro Seru", cat: "Ultah", price: 225000 },
  { preview: "preview/ultah-08-gala-malam.jpg", file: "ultah-08-gala-malam.html", name: "Gala Malam", cat: "Ultah", price: 300000 },
  { preview: "preview/ultah-09-karnaval.jpg", file: "ultah-09-karnaval.html", name: "Karnaval", cat: "Ultah", price: 300000 },
  { preview: "preview/ultah-10-bintang-pesta.jpg", file: "ultah-10-bintang-pesta.html", name: "Bintang Pesta", cat: "Ultah", price: 300000 },
  { preview: "preview/wisuda-01-toga-emas.jpg", file: "wisuda-01-toga-emas.html", name: "Toga Emas", cat: "Wisuda", price: 150000 },
  { preview: "preview/wisuda-02-putih-toga.jpg", file: "wisuda-02-putih-toga.html", name: "Putih Toga", cat: "Wisuda", price: 150000 },
  { preview: "preview/wisuda-03-biru-kampus.jpg", file: "wisuda-03-biru-kampus.html", name: "Biru Kampus", cat: "Wisuda", price: 150000 },
  { preview: "preview/wisuda-04-abu-akademik.jpg", file: "wisuda-04-abu-akademik.html", name: "Abu Akademik", cat: "Wisuda", price: 225000 },
  { preview: "preview/wisuda-05-marun-ilmiah.jpg", file: "wisuda-05-marun-ilmiah.html", name: "Marun Ilmiah", cat: "Wisuda", price: 225000 },
  { preview: "preview/wisuda-06-hijau-almamater.jpg", file: "wisuda-06-hijau-almamater.html", name: "Hijau Almamater", cat: "Wisuda", price: 225000 },
  { preview: "preview/wisuda-07-hitam-formal.jpg", file: "wisuda-07-hitam-formal.html", name: "Hitam Formal", cat: "Wisuda", price: 225000 },
  { preview: "preview/wisuda-08-rektorat-agung.jpg", file: "wisuda-08-rektorat-agung.html", name: "Rektorat Agung", cat: "Wisuda", price: 300000 },
  { preview: "preview/wisuda-09-laurel-emas.jpg", file: "wisuda-09-laurel-emas.html", name: "Laurel Emas", cat: "Wisuda", price: 300000 },
  { preview: "preview/wisuda-10-menara-ilmu.jpg", file: "wisuda-10-menara-ilmu.html", name: "Menara Ilmu", cat: "Wisuda", price: 300000 },
];

function formatRp(n) {
  return 'Rp' + n.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '.');
}
